### ISSUE TITLE
ifconfig: command not found

### ISSUE THREAD

**Issue by hendrik77** [brandoncaulfield/sap-nw-abap-trial-docker-windows#6]
hi,

when running the ./install.sh command it ends with an error:
> ./install.sh: line 77: ifconfig: command not found

The reason seems to be that the net-tools including ifconfig have been deprecated - see this [link](http://www.freetechie.com/blog/opensuse-tumbleweed-net-tools-vs-net-tools-deprecated/)

My solution was to install the deprecated net-tools:
> zypper install net-tools-deprecated

Best Regards
Hendrik

**Comment by brandoncaulfield** [comment]
Thanks @hendrik77 ! Appreciate the feedback :)
